#!/bin/ksh
############################################################
#       File:       calc.sh
#       Purpose:    Database Calc Kickoff & Notifications
#
#       Version:
#       Parameters:
#       Created:
#       Author:   mbowen@mdcbowen.org
#       Parameters:
#       User to run with: essbase
#
#	modified 20030425.0930 by mbowen
#
############################################################

## this version should run on any box

appid=$1
# whereami
disk=`head -1 ~essbase/disk.dat`
envid=`head -1 ~essbase/env.dat`


errdir="/${disk}03/essbase/rdwmr/errlogs/"
logdir="/${disk}03/essbase/rdwmr/logs/"
expdir="/${disk}03/essbase/rdwmr/export/"
appdir="/${disk}01/vendors/essbase/app/"
scrdir="/${disk}03/essbase/rdwmr/scripts/"
inpdir="/${disk}03/essbase/rdwmr/input/"
bindir="/${disk}01/vendors/essbase/bin/"


rfin_companies="ana das ims nna nmac ncc ncfi nda nesci nmic nesco nmch nmex nmcic nmisc ntcna nmihc nca nci"
recipients='bowenm@nmc.nna, mcdougm@nmc.nna'

logfile="${logdir}calc_activity.log"

## subs
log () {
	TIMESTAMP=`date '+%m/%d/%Y %H:%M:%S'`
	echo "${TIMESTAMP} ${PGMNAME} ${PID} $*" >>$logfile
}


## app parse
case $appid in
	'mex6')   xapp="MEX6";  db="Main";  csc="c_main"; valid=1;;
	'rbs')   xapp="RBS";  db="Main";  csc="c_main"; valid=1;;
	'rbsc')   xapp="RBSC";  db="Main";  csc="c_main"; valid=0;;
	'rfem')   xapp="RFEM";  db="Main";  csc="c_main"; valid=1;;
	'rx10')   xapp="RX10";  db="Main";  csc="c_main"; valid=1;;
	'rx11')   xapp="RX11";  db="Main";  csc="c_main"; valid=1;;
	'rpla')   xapp="RPLA";  db="Main";  csc="c_main"; valid=1;;
	'rplb')   xapp="RPLB";  db="Main";  csc="c_main"; valid=1;;
	'rplc')   xapp="RPLC";  db="Main";  csc="c_main"; valid=1;;
	'rplu')   xapp="RPLU";  db="Main";  csc="c_main"; valid=1;;
	'locl')  xapp="LOCL"; db="Main";  csc="c_main"; valid=1;;
	'patb')  xapp="PATB"; db="Main";  csc="c_main"; valid=1;;
	*)	valid=0;;
esac



## CALCULATION SECTION ## --------------------------------------------------------

if [[ valid -eq 1 ]]; then

	# MSH FABRICATION

	mshfile=${scrdir}${appid}_calc.msh

	echo "/* autogenerated by calc.sh `date` on $envid */" > $mshfile
	echo 'login system manager on localhost;' >> $mshfile

	echo " " >> $mshfile
	echo "execute calculation ${xapp}.${db}.${csc};" >> $mshfile
	echo " " >> $mshfile

	echo 'logout; exit;' >> $mshfile


	## RUN SPECIFIC CALC MSH

	echo calc.sh: calculating ${xapp}..
	log started calculating ${xapp}..
	# echo `date` | mailx -s "$envid $xapp Calc Initiated" $recipients

	cd $scrdir

	${bindir}essmsh ${appid}_calc.msh > ${logdir}${appid}_calc.log
	${scrdir}stats.sh $appid >> ${logdir}${appid}_calc.log


	## NOTIFY OF THE CALC
	log finished calculating ${xapp}
	echo calc.sh: finished calculating ${xapp}

	cd ${logdir}
	cat ${appid}_calc.log | mailx -s "$envid $xapp Calc Complete" $recipients
	perl ${scrdir}arc.pl ${appid}_calc.log

else

	echo invalid selection for calc.sh of $appid
	log invalid selection for calc.sh of $appid


fi


