#!/bin/ksh
############################################################
#       File:       extract.sh
#       Purpose:    Limited Extract for RFEM Closed Loop
#
#       Version:
#       Parameters:
#       Created:  20030707.0927
#       Author:   mbowen@mdcbowen.org
#       Parameters:
#       User to run with: essbase
#
#	modified 20030707.0927 by mbowen
#
############################################################
# Regional DW Export Control
#
# 20030707.0927 - mbowen@mdcbowen.org
# for Nissan USA
#
############################################################

# good for all boxes

## init
# whereami
disk=`head -1 ~essbase/disk.dat`
envid=`head -1 ~essbase/env.dat`


# some handy constants
PGMNAME=`basename $0`
PID=$$

appid="rfem"
xapp="RFEM"
xdate=$1


errdir="/${disk}03/essbase/rdwmr/errlogs/"
logdir="/${disk}03/essbase/rdwmr/logs/"
expdir="/${disk}03/essbase/rdwmr/export/"
outdir="/${disk}02/staging/nardw/FileXfer/Xferin/Elim/"
#outdir="/${disk}03/essbase/rdwmr/output/"
appdir="/${disk}01/vendors/essbase/app/"
scrdir="/${disk}03/essbase/rdwmr/scripts/"
inpdir="/${disk}03/essbase/rdwmr/input/"
bindir="/${disk}01/vendors/essbase/bin/"

recipients='bowenm@nmc.nna, schwabj@nmc.nna, mcdougm@nmc.nna'

logfile="${logdir}rfemx_activity.log"

## subs
log () {
	TIMESTAMP=`date '+%m/%d/%Y %H:%M:%S'`
	echo "${TIMESTAMP} ${PGMNAME} ${PID} $*" >>$logfile
}



makemsh () {

	app=$1
	mshfile="${app}_extract.msh"
	echo generating $mshfile
	echo "/* autogenerated by extract.sh `date` */" > $mshfile
	echo "login system manager on localhost;" >> $mshfile

	echo "alter application $xapp disable connects;" >> $mshfile
	echo "alter system logout session on application ${xapp};" >> $mshfile

	# export to extract
	echo "export database ${xapp}.Main" >> $mshfile
	echo "input data in columns to data_file " >> $mshfile

	a="'${outdir}man_entry_elim.txt';"
	echo "$a" >> $mshfile

	echo "alter application ${xapp} enable connects;" >> $mshfile
	echo "logout; exit;" >> $mshfile

}



## main
clear


echo ${appid} extract initiated
log ${appid} extract initiated
cd $scrdir

## data export using internally generated msh

makemsh ${appid}
date > ${logdir}${appid}_extract.log
echo $envid >> ${logdir}${appid}_extract.log
echo '$$Current_DT='$xdate >> ${logdir}${appid}_extract.log

echo extracting data..
${bindir}essmsh ${scrdir}${appid}_extract.msh >> ${logdir}${appid}_extract.log
echo done.


## notify and archive log
cd ${logdir}
cat ${appid}_extract.log | mailx -s "${envid} ${xapp} Extract" $recipients
perl ${scrdir}arc.pl ${appid}_extract.log

## make token
tfile="${outdir}man_entry_elim.tok"

echo '[s_m_ELIM_HYP_INPUT_MANUAL_ENTRY]' > $tfile
echo '$$Current_DT='$xdate >> $tfile
#echo '[s_m_ELIM_HYP_Extract_6DIGIT_ME]' >> $tfile
#echo '$$Current_DT='$xdate >> $tfile

echo rfemx.sh: '$$Current_DT='$xdate

ls -lt ${outdir}man_*

                                                                                      