#!/usr/bin/perl
#
# AIX version 
# updated - 20030311 - mb@mdcbowen.org
# for NISSAN-USA
#
######################

# this proc will eyeball a tokenfile and interpret the date
# then convert it into several substitution variables via the
# creation and then running of a maxl script

# this proc is called by prepoll.sh depending on whether its output
# subvar.msh exists already
	


$file = shift @ARGV; 
$file || die "usage: subvar.pl filespec\n";
$infile = $file;

$go = 0;
open (TOKEN, "< $infile") || die "subvar.pl: token file unspec.\n";

while (<TOKEN>) {

	chop;
	if (/00/) {
		$line = $_;
		$go = 1;
	}	
}
close TOKEN;

if ($go) {
	&fixDates ($line);

	system ("essmsh subvar.msh");	
	 }
else {
	print "empty token.\n";	
}




sub fixDates {

	## this sub will take the string passed yyyy-mm format
	## and create the appropriate substitution variables through
	## the creation and running of a maxl script.
	local $pmo = $_[0];
	
	$l = localtime(time());
	
	print "$l\n\n";
	
	%mos =
	("Jan","01","Feb","02","Mar","03","Apr","04","May","05","Jun","06",
	"Jul","07","Aug","08","Sep","09","Oct","10","Nov","11","Dec","12");
	 
	
	$cent = substr($l,-4);
	# print "$cent\n";
	
	$hrs = substr($l,11,8);
	$hrs =~ s/\://g;
	#print "$hrs\n";
	
	$nmo = substr($l,4,3);
	$mo = $mos{$nmo};
	#print "$mo\n";
	
	$da = substr($l,8,2);
	$da =~ s/\D/0/;
	
	$yy = substr($cent,-2);
	
	$outtime = "$cent$mo$da-$hrs";
	
	
	$py = $cent-1;
	#print "Prior Year: $py\n";
	
	$currMo = "$cent-$mo";
	#print "Current Month: $currMo\n";
	
	
	$currMo = $pmo;
	print "i saw $pmo.\n";
	
	
	open (T, "< cal_table.txt")|| die "calendar table missing.\n";
	while (<T>) {
		chop;
		@line = split (/\t/,$_,7);
		if (/^$currMo/) {
			#print "aha\n";
			print "$line[6]\n";
			$cp = $line[0];
			$cq = $line[1];
			$py = $line[2];
			$bp = $line[5];
			$bq = $line[6];
			$mcq = $line[1];
			$mbp = $line[3];
			$mbq = $line[4];
			
		}
	}
	close T;
	
	
	print "bq: $bq\n";
	
	
	$am = "alter database MEX6.Main add variable";
	$ar = "alter database RFIN.Main add variable";
	
	$dm = "alter database MEX6.Main drop variable";
	$dr = "alter database RFIN.Main drop variable";
	open (OUT, "> subvar.msh");
	
	print OUT "/* autogenerated by subvar.pl $l */\n";
	print OUT "login 'system' 'manager' on 'localhost';\n";
	
	print OUT "$dm CurrentPeriod;\n";
	print OUT "$dm CurrentQTR;\n";
	print OUT "$dm PriorYRMO ;\n";
	print OUT "$dm BeginPeriod;\n";
	print OUT "$dm BeginQTR ;\n";
	
	print OUT "$dr CurrentPeriod;\n";
	print OUT "$dr CurrentQTR;\n";
	print OUT "$dr PriorYRMO;\n";
	print OUT "$dr BeginPeriod;\n";
	print OUT "$dr BeginQTR;\n";
	
	
	print OUT "$am CurrentPeriod '$cp';\n";
	print OUT "$am CurrentQTR '$mcq';\n";
	print OUT "$am PriorYRMO '$py';\n";
	print OUT "$am BeginPeriod '$mbp';\n";
	print OUT "$am BeginQTR '$mbq';\n";
	
	print OUT "$ar CurrentPeriod '$cp';\n";
	print OUT "$ar CurrentQTR '$cq';\n";
	print OUT "$ar PriorYRMO '$py';\n";
	print OUT "$ar BeginPeriod '$bp';\n";
	print OUT "$ar BeginQTR '$bq';\n";
	
	print OUT "logout; exit;\n";
	close OUT;
	
	print "done.\n";
	


}	
